import type { Metadata } from "next";

// import font
import { Poppins } from "next/font/google";

// import css
import "./globals.css";

// import components
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import ContactModal from "@/components/modal";

const poppins = Poppins({
  weight: ['400','500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Dopamine",
  description: "Generated by Dopamine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/icon.png" sizes="any" />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className={poppins.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
        <ContactModal />
        <Footer />
      </body>
    </html>
  );
}
